<?php
  class Colors1{
    // Declare constants of colors. One will make those NAVBAR_BASE_COLOR stuff
    // and the other will set values for them.

  	//INDEX PAGE
    public const INDEX_PAGE_EVENT_NAME_COLOR = #000000;
    public const INDEX_PAGE_SEARCH_CONTAINER = #000000;
    public const INDEX_PAGE_POINTER_HOVER_COLOR = #000000;
    public const INDEX_PAGE_EVENT_TABLE_FONT_COLOR = #000000;
    public const INDEX_PAGE_INNER_HEADER_COLOR = #000000;

    //INDEX PAGE - NAVBAR
    public const NAVBAR_BASE_COLOR = #e0e0e0;
    public const NAVBAR_SHADOW_COLOR = #000000;
    public const NAVBAR_FONT_COLOR = #000000;
    public const NAVBAR_BUTTON_COLOR = #000000;
    public const NAVBAR_BUTTON_FONT_COLOR = #000000;

    //INDEX PAGE - FOOTER
    public const FOOTER = #000000;
    public const FOOTER_FONT_COLOR = #000000;
    public const FOOTER_BUTTON_COLOR = #000000;

    //LOGIN PAGE
    public const LOGIN_BACKGROUND_COLOR = #000000;
  	public const LOGIN_BUTTON_COLOR = #000000;
  	public const LOGIN_BUTTON_FONT_COLOR = #000000;
  	public const LOGIN_BUTTON_BACKGROUND_COLOR = #000000;
  	public const LOGIN_FONT_COLOR = #000000;

  	//USER PAGE
  	public const USER_PAGE_FONT_COLOR = #0;
  	public const USER_PAGE_HEADER_CONNECT_COLOR = #000000;
  	public const USER_PAGE_DIV_SEARCH_BOX_COLOR = #000000;
  	public const USER_PAGE_DIV_SEARCH_BOX_BUTTON_COLOR = #000000;
  	public const USER_PAGE_DIV_SEARCH_BOX_FONT_COLOR = #000000;
  	public const USER_PAGE_EVENT_SORT_BUTTON_INACTIVE_COLOR = #000000;
  	public const USER_PAGE_EVENT_SORT_BUTTON_ACTIVE_COLOR = #000000;
  	public const USER_PAGE_EVENT_NAME_COLOR = #000000;
  	public const USER_PAGE_EVENT_DATE_COLOR = #000000;
  	public const USER_PAGE_EVENT_BORDER_COLOR = #000000;
  	public const USER_PAGE_EVENT_VIEW_ACTIVE_COLOR = #000000;
  	public const USER_PAGE_EVENT_VIEW_INACTIVE_COLOR = #000000;
  	public const USER_PAGE_EVENT_PAGINATION_COLOR = #000000;
  	public const USER_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = #000000;
  	public const USER_PAGE_EVENT_PAGINATION_HOVER_COLOR = #000000;

  	//EVENT PAGE
  	public const EVENT_PAGE_HEADER_COLOR = #000000;
  	public const EVENT_PAGE_HEADER_FONT_COLOR = #000000;
  	public const EVENT_PAGE_BACKGROUND_COLOR = #000000;
  	public const EVENT_PAGE_FONT_COLOR= #000000;
  	public const EVENT_PAGE_FONT_HEADER_COLOR = #000000;
  	public const EVENT_PAGE_ADDTIONAL_DETAILS_BACKGROUND_COLOR = #000000;
  	public const EVENT_PAGE_ADDITIONAL_DETAILS_FONT_COLOR = #000000;
  	public const EVENT_PAGE_USER_DETAILS_BACKGROUND_COLOR = #000000;
  	public const EVENT_PAGE_USER_DETAILS_FONT_HEADER_COLOR = #000000;
  	public const EVENT_PAGE_USER_DETAILS_FONT_COLOR = #000000;
  	public const EVENT_PAGE_USER_DETAILS_BUTTON_COLOR = #000000;
  	public const EVENT_PAGE_USER_DETAILS_BUTTON_FONT_COLOR = #000000;
  	public const EVENT_PAGE_TICKET_DETAILS_BACKGROUND_COLOR = #000000;
  	public const EVENT_PAGE_TICKET_DETAILS_FONT_COLOR = #000000;
  	public const EVENT_PAGE_TICKET_DETAILS_FONT_HEADER_COLOR = #000000;
  	public const EVENT_PAGE_TICKET_DETAILS_BUTTON_COLOR = #000000;
  	public const EVENT_PAGE_TICKET_DETAILS_BUTTON_FONT_COLOR = #000000;


  	//PROFILE PAGE
  	public const PROFILE_PAGE_HEADER_COLOR = #000000;
  	public const PROFILE_PAGE_HEAD_FONT_COLOR = #000000;
  	public const PROFILE_PAGE_FONT_COLOR = #000000;
  	public const PROFILE_PAGE_FONT_HEADER_COLOR = #000000;
  	public const PROFILE_PAGE_BACKGROUND_COLOR = #000000;
  	public const PROFILE_PAGE_BUTTON_COLOR = #000000;
  	public const PROFILE_PAGE_BUTTON_FONT_COLOR = #000000;
  	public const PROFILE_PAGE_TABS_ACTIVE_COLOR = #000000;
  	public const PROFILE_PAGE_TABS_INACTIVE_COLOR = #000000;
  	public const PROFILE_PAGE_VIEW_ACTIVE_COLOR = #000000;
  	public const PROFILE_PAGE_VIEW_INACTIVE_COLOR = #000000;
  	public const PROFILE_PAGE_VIEW_HOVER_COLOR = #000000;

  	//PROFILE PAGE - EVENT TABLE
  	public const PROFILE_PAGE_EVENT_NAME_COLOR = #000000;
  	public const PROFILE_PAGE_EVENT_DATE_COLOR = #000000;
  	public const PROFILE_PAGE_EVENT_STATUS = #000000;
  	public const PROFILE_PAGE_EVENT_PAGINATION_COLOR = #000000;
  	public const PROFILE_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = #000000;
  	public const PROFILE_PAGE_EVENT_PAGINATION_HOVER_COLOR = #000000;

  	//PROFILE PAGE - REPORT TABLE
  	public const PROFILE_PAGE_REPORT_TABLE_HEADER_BACKGROUND_COLOR = #000000;
  	public const PROFILE_PAGE_REPORT_TABLE_HEADER_FONT_COLOR = #000000;
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR1 = #0;
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR2 = #0;
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_FONT_COLOR = #0;
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_FONT_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_HEADER_FONT_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_HEADER_FONT_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR1 = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR2 = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_FONT_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BUTTON_COLOR = #0;
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BUTTON_FONT_COLOR = #0;

	//PROFILE PAGE - PAYMENT HISTORY
	public const PROFILE_PAGE_PAYHIST_TABLE_HEADER_FONT_COLOR = #0;
	public const PROFILE_PAGE_PAYHIST_TABLE_DATA_FONT_COLOR = #0;

	//CREATE EVENT
	public const PROFILE_PAGE_CREATE_EVENT_HEADER_BACKGROUND_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_HEADER_FONT_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_FORM_HEADER_FONT_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_FONT_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_BORDER_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_BUTTON_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_BUTTON_FONT_COLOR= #0;
	public const PROFILE_PAGE_CREATE_EVENT_FOOTER_BACKGROUND_COLOR = #0;
	public const PROFILE_PAGE_CREATE_EVENT_FOOTER_FONT_COLOR = #0;

	//ADMIN PAGE
	public const ADMIN_PAGE_HEADER_COLOR = #0;
	public const ADMIN_PAGE_SIDEBAR_BACKGROUND_COLOR = #0;
	public const ADMIN_PAGE_SIDEBAR_FONT_COLOR = #0;
	public const ADMIN_PAGE_SIDEBAR_ACTIVE_COLOR = #0;
	public const ADMIN_PAGE_SIDEBAR_INACTIVE_COLOR = #0;
	public const ADMIN_PAGE_SIDEBAR_HOVER_COLOR = #0;

	//ADMIN PAGE - EVENT PAGE
	public const ADMIN_PAGE_EVENT_FONT_HEADER_COLOR = #0;
	public const ADMIN_PAGE_EVENT_TABLE_HEADER_FONT_COLOR = #0;
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR1 = #0;
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR2 = #0;
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR1 = #0;
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR2 = #0;
	public const ADMIN_PAGE_EVENT_TABLE_DATA_FONT_COLOR = #0;

	//ADMIN PAGE - USER MANAGEMENT
	public const ADMIN_PAGE_USER_FONT_HEADER_COLOR = #0;
	public const ADMIN_PAGE_USER_TABLE_HEADER_COLOR = #0;
	public const ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR1 = #0;
	public const ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR2 = #0;
	public const ADMIN_PAGE_USER_TABLE_DATA_BUTTON_COLOR1 = #0;
	public const ADMIN_PAGE_USER_TABLE_DATA_FONT_COLOR = #0;

	//ADMIN PAGE - ADMIN MANAGEMENT
	public const ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR = #0;
	public const ADMIN_PAGE_ADMIN_TABLE_HEADER_FONT_COLOR = #0;
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR1 = #0;
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR2 = #0;
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR1 = #0;
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR2 = #0;
	public const ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR_TABLE_DATA_FONT_COLOR = #0;
  }
?>
