<?php
  class Colors1{
    // Declare constants of colors. One will make those NAVBAR_BASE_COLOR stuff
    // and the other will set values for them.
   
  	//INDEX PAGE
    public const INDEX_PAGE_EVENT_NAME_COLOR = "#ffffff";
    public const INDEX_PAGE_SEARCH_CONTAINER = "#ffffff";
    public const INDEX_PAGE_POINTER_HOVER_COLOR = "#cccccc";
    public const INDEX_PAGE_EVENT_TABLE_FONT_COLOR = "#000000";
    public const INDEX_PAGE_INNER_HEADER_COLOR = "#cccccc";

    //INDEX PAGE - NAVBAR
    public const NAVBAR_BASE_COLOR = "#675682";
    public const NAVBAR_SHADOW_COLOR = "#d98cd9";
    public const NAVBAR_FONT_COLOR = "#ffffff";
    public const NAVBAR_BUTTON_COLOR = "#e52a6f";
    public const NAVBAR_BUTTON_FONT_COLOR = "#ffffff";

    //INDEX PAGE - FOOTER
    public const FOOTER = "#675682";
    public const FOOTER_FONT_COLOR = "#ffffff";
    public const FOOTER_BUTTON_COLOR = "#e52a6f";

    //LOGIN PAGE
    public const LOGIN_BACKGROUND_COLOR = "#675682";
  	public const LOGIN_BUTTON_COLOR = "#e52a6f";
  	public const LOGIN_BUTTON_FONT_COLOR = "#ffffff";
  	public const LOGIN_BUTTON_BACKGROUND_COLOR = "#000000";
  	public const LOGIN_FONT_COLOR = "#000000";

  	//USER PAGE
  	public const USER_PAGE_FONT_COLOR = "#000000";
  	public const USER_PAGE_HEADER_CONNECT_COLOR = "#ffffff";
  	public const USER_PAGE_DIV_SEARCH_BOX_COLOR = "#ffffff";
  	public const USER_PAGE_DIV_SEARCH_BOX_BUTTON_COLOR = "#e52a6f";
  	public const USER_PAGE_DIV_SEARCH_BOX_FONT_COLOR = "#cccccc";
  	public const USER_PAGE_EVENT_SORT_BUTTON_INACTIVE_COLOR = "#bfbfbf";
  	public const USER_PAGE_EVENT_SORT_BUTTON_ACTIVE_COLOR = "#808080";
  	public const USER_PAGE_EVENT_NAME_COLOR = "#000000";
  	public const USER_PAGE_EVENT_DATE_COLOR = "#000000";
  	public const USER_PAGE_EVENT_BORDER_COLOR = "#000000";
  	public const USER_PAGE_EVENT_VIEW_ACTIVE_COLOR = "#808080";
  	public const USER_PAGE_EVENT_VIEW_INACTIVE_COLOR = "#bfbfbf";
  	public const USER_PAGE_EVENT_PAGINATION_COLOR = "#67aeca";
  	public const USER_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = "#357b97";
  	public const USER_PAGE_EVENT_PAGINATION_HOVER_COLOR = "#6aafc8";

  	//EVENT PAGE
  	public const EVENT_PAGE_HEADER_COLOR = "#67aeca";
  	public const EVENT_PAGE_HEADER_FONT_COLOR = "#ffffff";
  	public const EVENT_PAGE_BACKGROUND_COLOR = "#675682";
  	public const EVENT_PAGE_FONT_COLOR= "#ffffff";
  	public const EVENT_PAGE_FONT_HEADER_COLOR = "#000000";
  	public const EVENT_PAGE_ADDTIONAL_DETAILS_BACKGROUND_COLOR = "#ffffff";
  	public const EVENT_PAGE_ADDITIONAL_DETAILS_FONT_COLOR = "#000000";
  	public const EVENT_PAGE_USER_DETAILS_BACKGROUND_COLOR = "#ffffff";
  	public const EVENT_PAGE_USER_DETAILS_FONT_HEADER_COLOR = "#000000";
  	public const EVENT_PAGE_USER_DETAILS_FONT_COLOR = "#000000";
  	public const EVENT_PAGE_USER_DETAILS_BUTTON_COLOR = "#e52a6f";
  	public const EVENT_PAGE_USER_DETAILS_BUTTON_FONT_COLOR = "#ffffff";
  	public const EVENT_PAGE_TICKET_DETAILS_BACKGROUND_COLOR = "#5f0f4e";
  	public const EVENT_PAGE_TICKET_DETAILS_FONT_COLOR = "#ffffff";
  	public const EVENT_PAGE_TICKET_DETAILS_FONT_HEADER_COLOR = "#ffffff";
  	public const EVENT_PAGE_TICKET_DETAILS_BUTTON_COLOR = "#e52a6f";
  	public const EVENT_PAGE_TICKET_DETAILS_BUTTON_FONT_COLOR = "#ffffff";


  	//PROFILE PAGE
  	public const PROFILE_PAGE_HEADER_COLOR = "#67aeca";
  	public const PROFILE_PAGE_HEAD_FONT_COLOR = "#ffffff";
  	public const PROFILE_PAGE_FONT_COLOR = "#000000";
  	public const PROFILE_PAGE_FONT_HEADER_COLOR = "#000000";
  	public const PROFILE_PAGE_BACKGROUND_COLOR = "#ffffff";
  	public const PROFILE_PAGE_BUTTON_COLOR = "#e52a6f";
  	public const PROFILE_PAGE_BUTTON_FONT_COLOR = "#ffffff";
  	public const PROFILE_PAGE_TABS_ACTIVE_COLOR = "#808080";
  	public const PROFILE_PAGE_TABS_INACTIVE_COLOR = "#bfbfbf";
  	public const PROFILE_PAGE_VIEW_ACTIVE_COLOR = "#808080";
  	public const PROFILE_PAGE_VIEW_INACTIVE_COLOR = "#bfbfbf";
  	public const PROFILE_PAGE_VIEW_HOVER_COLOR = "#6aafc8";

  	//PROFILE PAGE - EVENT TABLE
  	public const PROFILE_PAGE_EVENT_NAME_COLOR = "#000000";
  	public const PROFILE_PAGE_EVENT_DATE_COLOR = "#000000";
  	public const PROFILE_PAGE_EVENT_STATUS = "#e52a6f";
  	public const PROFILE_PAGE_EVENT_PAGINATION_COLOR = "#67aeca";
  	public const PROFILE_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = "#808080";
  	public const PROFILE_PAGE_EVENT_PAGINATION_HOVER_COLOR = "#6aafc8";

  	//PROFILE PAGE - REPORT TABLE
  	public const PROFILE_PAGE_REPORT_TABLE_HEADER_BACKGROUND_COLOR = "#5f0f4e";
  	public const PROFILE_PAGE_REPORT_TABLE_HEADER_FONT_COLOR = "#ffffff";
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_FONT_COLOR = "#000000";
  	public const PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_COLOR = "#e52a6f";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_FONT_COLOR = "#ffffff";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_HEADER_FONT_COLOR = "#000000";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_HEADER_FONT_COLOR = "#000000";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR1 = "#cccccc";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR2 = "#";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_FONT_COLOR = "#cccccc";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GEN ERATED_TABLE_DATA_BUTTON_COLOR = "#e52a6f";
	public const PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BUTTON_FONT_COLOR = "#ffffff";

	//PROFILE PAGE - PAYMENT HISTORY
	public const PROFILE_PAGE_PAYHIST_TABLE_HEADER_FONT_COLOR = "#000000";
	public const PROFILE_PAGE_PAYHIST_TABLE_DATA_FONT_COLOR = "#cccccc";

	//CREATE EVENT
	public const PROFILE_PAGE_CREATE_EVENT_HEADER_BACKGROUND_COLOR = "#67aeca";
	public const PROFILE_PAGE_CREATE_EVENT_HEADER_FONT_COLOR = "#ffffff";
	public const PROFILE_PAGE_CREATE_EVENT_FORM_HEADER_FONT_COLOR = "#000000";
	public const PROFILE_PAGE_CREATE_EVENT_FONT_COLOR = "#000000";
	public const PROFILE_PAGE_CREATE_EVENT_BORDER_COLOR = "#000000";
	public const PROFILE_PAGE_CREATE_EVENT_BUTTON_COLOR = "#e52a6f";
	public const PROFILE_PAGE_CREATE_EVENT_BUTTON_FONT_COLOR= "#ffffff";
	public const PROFILE_PAGE_CREATE_EVENT_FOOTER_BACKGROUND_COLOR = "#675682";
	public const PROFILE_PAGE_CREATE_EVENT_FOOTER_FONT_COLOR = "#ffffff";

	//ADMIN PAGE
	public const ADMIN_PAGE_HEADER_COLOR = "#67aeca";
	public const ADMIN_PAGE_SIDEBAR_BACKGROUND_COLOR = "#5f0f4e";
	public const ADMIN_PAGE_SIDEBAR_FONT_COLOR = "#ffffff";
	public const ADMIN_PAGE_SIDEBAR_ACTIVE_COLOR = "#bfbfbf";
	public const ADMIN_PAGE_SIDEBAR_INACTIVE_COLOR = "#808080";
	public const ADMIN_PAGE_SIDEBAR_HOVER_COLOR = "#6aafc8";

	//ADMIN PAGE - EVENT PAGE
	public const ADMIN_PAGE_EVENT_FONT_HEADER_COLOR = "#000000";
	public const ADMIN_PAGE_EVENT_TABLE_HEADER_FONT_COLOR = "#000000";
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
	public const ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR2 = "#e52a6f";
	public const ADMIN_PAGE_EVENT_TABLE_DATA_FONT_COLOR = "#000000";

	//ADMIN PAGE - USER MANAGEMENT
	public const ADMIN_PAGE_USER_FONT_HEADER_COLOR = "#000000";
	public const ADMIN_PAGE_USER_TABLE_HEADER_COLOR = "#ffffff";
	public const ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
	public const ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR2 = "#ffffff";
	public const ADMIN_PAGE_USER_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
	public const ADMIN_PAGE_USER_TABLE_DATA_FONT_COLOR = "#ffffff";
  
	//ADMIN PAGE - ADMIN MANAGEMENT
	public const ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR = "#000000";
	public const ADMIN_PAGE_ADMIN_TABLE_HEADER_FONT_COLOR = "#000000";
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
	public const ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR2 = "#e52a6f";
	public const ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR_TABLE_DATA_FONT_COLOR = "#cccccc";
  }
?>
