<?php
  class Colors2{
    // Declare constants of colors. One will make those NAVBAR_BASE_COLOR stuff
    // and the other will set values for them.

  	//INDEX PAGE
    public $INDEX_PAGE_EVENT_NAME_COLOR = "#ffffff";
    public $INDEX_PAGE_SEARCH_CONTAINER = "#ffffff";
    public $INDEX_PAGE_POINTER_HOVER_COLOR = "#cccccc";
    public $INDEX_PAGE_EVENT_TABLE_FONT_COLOR = "#000000";
    public $INDEX_PAGE_INNER_HEADER_COLOR = "#cccccc";

    //INDEX PAGE - NAVBAR
    public $NAVBAR_BASE_COLOR = "#675682";
    public $NAVBAR_SHADOW_COLOR = "#d98cd9";
    public $NAVBAR_FONT_COLOR = "#ffffff";
    public $NAVBAR_BUTTON_COLOR = "#e52a6f";
    public $NAVBAR_BUTTON_FONT_COLOR = "#ffffff";

    //INDEX PAGE - FOOTER
    public $FOOTER = "#675682";
    public $FOOTER_FONT_COLOR = "#ffffff";
    public $FOOTER_BUTTON_COLOR = "#e52a6f";

    //LOGIN PAGE
    public $LOGIN_BACKGROUND_COLOR = "#675682";
  	public $LOGIN_BUTTON_COLOR = "#e52a6f";
  	public $LOGIN_BUTTON_FONT_COLOR = "#ffffff";
  	public $LOGIN_BUTTON_BACKGROUND_COLOR = "#000000";
  	public $LOGIN_FONT_COLOR = "#000000";

  	//USER PAGE
  	public $USER_PAGE_FONT_COLOR = "#000000";
  	public $USER_PAGE_HEADER_CONNECT_COLOR = "#ffffff";
  	public $USER_PAGE_DIV_SEARCH_BOX_COLOR = "#ffffff";
  	public $USER_PAGE_DIV_SEARCH_BOX_BUTTON_COLOR = "#e52a6f";
  	public $USER_PAGE_DIV_SEARCH_BOX_FONT_COLOR = "#cccccc";
  	public $USER_PAGE_EVENT_SORT_BUTTON_INACTIVE_COLOR = "#bfbfbf";
  	public $USER_PAGE_EVENT_SORT_BUTTON_ACTIVE_COLOR = "#808080";
  	public $USER_PAGE_EVENT_NAME_COLOR = "#000000";
  	public $USER_PAGE_EVENT_DATE_COLOR = "#000000";
  	public $USER_PAGE_EVENT_BORDER_COLOR = "#000000";
  	public $USER_PAGE_EVENT_VIEW_ACTIVE_COLOR = "#808080";
  	public $USER_PAGE_EVENT_VIEW_INACTIVE_COLOR = "#bfbfbf";
  	public $USER_PAGE_EVENT_PAGINATION_COLOR = "#67aeca";
  	public $USER_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = "#357b97";
  	public $USER_PAGE_EVENT_PAGINATION_HOVER_COLOR = "#6aafc8";

  	//EVENT PAGE
  	public $EVENT_PAGE_HEADER_COLOR = "#67aeca";
  	public $EVENT_PAGE_HEADER_FONT_COLOR = "#ffffff";
  	public $EVENT_PAGE_BACKGROUND_COLOR = "#675682";
  	public $EVENT_PAGE_FONT_COLOR= "#ffffff";
  	public $EVENT_PAGE_FONT_HEADER_COLOR = "#000000";
  	public $EVENT_PAGE_ADDTIONAL_DETAILS_BACKGROUND_COLOR = "#ffffff";
  	public $EVENT_PAGE_ADDITIONAL_DETAILS_FONT_COLOR = "#000000";
  	public $EVENT_PAGE_USER_DETAILS_BACKGROUND_COLOR = "#ffffff";
  	public $EVENT_PAGE_USER_DETAILS_FONT_HEADER_COLOR = "#000000";
  	public $EVENT_PAGE_USER_DETAILS_FONT_COLOR = "#000000";
  	public $EVENT_PAGE_USER_DETAILS_BUTTON_COLOR = "#e52a6f";
  	public $EVENT_PAGE_USER_DETAILS_BUTTON_FONT_COLOR = "#ffffff";
  	public $EVENT_PAGE_TICKET_DETAILS_BACKGROUND_COLOR = "#5f0f4e";
  	public $EVENT_PAGE_TICKET_DETAILS_FONT_COLOR = "#ffffff";
  	public $EVENT_PAGE_TICKET_DETAILS_FONT_HEADER_COLOR = "#ffffff";
  	public $EVENT_PAGE_TICKET_DETAILS_BUTTON_COLOR = "#e52a6f";
  	public $EVENT_PAGE_TICKET_DETAILS_BUTTON_FONT_COLOR = "#ffffff";


  	//PROFILE PAGE
  	public $PROFILE_PAGE_HEADER_COLOR = "#67aeca";
  	public $PROFILE_PAGE_HEAD_FONT_COLOR = "#ffffff";
  	public $PROFILE_PAGE_FONT_COLOR = "#000000";
  	public $PROFILE_PAGE_FONT_HEADER_COLOR = "#000000";
  	public $PROFILE_PAGE_BACKGROUND_COLOR = "#ffffff";
  	public $PROFILE_PAGE_BUTTON_COLOR = "#e52a6f";
  	public $PROFILE_PAGE_BUTTON_FONT_COLOR = "#ffffff";
  	public $PROFILE_PAGE_TABS_ACTIVE_COLOR = "#808080";
  	public $PROFILE_PAGE_TABS_INACTIVE_COLOR = "#bfbfbf";
  	public $PROFILE_PAGE_VIEW_ACTIVE_COLOR = "#808080";
  	public $PROFILE_PAGE_VIEW_INACTIVE_COLOR = "#bfbfbf";
  	public $PROFILE_PAGE_VIEW_HOVER_COLOR = "#6aafc8";

  	//PROFILE PAGE - EVENT TABLE
  	public $PROFILE_PAGE_EVENT_NAME_COLOR = "#000000";
  	public $PROFILE_PAGE_EVENT_DATE_COLOR = "#000000";
  	public $PROFILE_PAGE_EVENT_STATUS = "#e52a6f";
  	public $PROFILE_PAGE_EVENT_PAGINATION_COLOR = "#67aeca";
  	public $PROFILE_PAGE_EVENT_PAGINATION_ACTIVE_COLOR = "#808080";
  	public $PROFILE_PAGE_EVENT_PAGINATION_HOVER_COLOR = "#6aafc8";

  	//PROFILE PAGE - REPORT TABLE
  	public $PROFILE_PAGE_REPORT_TABLE_HEADER_BACKGROUND_COLOR = "#5f0f4e";
  	public $PROFILE_PAGE_REPORT_TABLE_HEADER_FONT_COLOR = "#ffffff";
  	public $PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
  	public $PROFILE_PAGE_REPORT_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
  	public $PROFILE_PAGE_REPORT_TABLE_DATA_FONT_COLOR = "#000000";
  	public $PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_COLOR = "#e52a6f";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_BUTTON_FONT_COLOR = "#ffffff";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_HEADER_FONT_COLOR = "#000000";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_HEADER_FONT_COLOR = "#000000";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR1 = "#cccccc";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BACKGROUND_COLOR2 = "#";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_FONT_COLOR = "#cccccc";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GEN_ERATED_TABLE_DATA_BUTTON_COLOR = "#e52a6f";
    public $PROFILE_PAGE_REPORT_TABLE_DATA_GENERATED_TABLE_DATA_BUTTON_FONT_COLOR = "#ffffff";

    //PROFILE PAGE - PAYMENT HISTORY
    public $PROFILE_PAGE_PAYHIST_TABLE_HEADER_FONT_COLOR = "#000000";
    public $PROFILE_PAGE_PAYHIST_TABLE_DATA_FONT_COLOR = "#cccccc";

    //CREATE EVENT
    public $PROFILE_PAGE_CREATE_EVENT_HEADER_BACKGROUND_COLOR = "#67aeca";
    public $PROFILE_PAGE_CREATE_EVENT_HEADER_FONT_COLOR = "#ffffff";
    public $PROFILE_PAGE_CREATE_EVENT_FORM_HEADER_FONT_COLOR = "#000000";
    public $PROFILE_PAGE_CREATE_EVENT_FONT_COLOR = "#000000";
    public $PROFILE_PAGE_CREATE_EVENT_BORDER_COLOR = "#000000";
    public $PROFILE_PAGE_CREATE_EVENT_BUTTON_COLOR = "#e52a6f";
    public $PROFILE_PAGE_CREATE_EVENT_BUTTON_FONT_COLOR= "#ffffff";
    public $PROFILE_PAGE_CREATE_EVENT_FOOTER_BACKGROUND_COLOR = "#675682";
    public $PROFILE_PAGE_CREATE_EVENT_FOOTER_FONT_COLOR = "#ffffff";

    //ADMIN PAGE
    public $ADMIN_PAGE_HEADER_COLOR = "#67aeca";
    public $ADMIN_PAGE_SIDEBAR_BACKGROUND_COLOR = "#5f0f4e";
    public $ADMIN_PAGE_SIDEBAR_FONT_COLOR = "#ffffff";
    public $ADMIN_PAGE_SIDEBAR_ACTIVE_COLOR = "#bfbfbf";
    public $ADMIN_PAGE_SIDEBAR_INACTIVE_COLOR = "#808080";
    public $ADMIN_PAGE_SIDEBAR_HOVER_COLOR = "#6aafc8";

    //ADMIN PAGE - EVENT PAGE
    public $ADMIN_PAGE_EVENT_FONT_HEADER_COLOR = "#000000";
    public $ADMIN_PAGE_EVENT_TABLE_HEADER_FONT_COLOR = "#000000";
    public $ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
    public $ADMIN_PAGE_EVENT_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
    public $ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
    public $ADMIN_PAGE_EVENT_TABLE_DATA_BUTTON_COLOR2 = "#e52a6f";
    public $ADMIN_PAGE_EVENT_TABLE_DATA_FONT_COLOR = "#000000";

    //ADMIN PAGE - USER MANAGEMENT
    public $ADMIN_PAGE_USER_FONT_HEADER_COLOR = "#000000";
    public $ADMIN_PAGE_USER_TABLE_HEADER_COLOR = "#ffffff";
    public $ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
    public $ADMIN_PAGE_USER_TABLE_DATA_BACKGROUND_COLOR2 = "#ffffff";
    public $ADMIN_PAGE_USER_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
    public $ADMIN_PAGE_USER_TABLE_DATA_FONT_COLOR = "#ffffff";

    //ADMIN PAGE - ADMIN MANAGEMENT
    public $ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR = "#000000";
    public $ADMIN_PAGE_ADMIN_TABLE_HEADER_FONT_COLOR = "#000000";
    public $ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR1 = "#ffffff";
    public $ADMIN_PAGE_ADMIN_TABLE_DATA_BACKGROUND_COLOR2 = "#cccccc";
    public $ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR1 = "#e52a6f";
    public $ADMIN_PAGE_ADMIN_TABLE_DATA_BUTTON_COLOR2 = "#e52a6f";
    public $ADMIN_PAGE_ADMIN_FONT_HEADER_COLOR_TABLE_DATA_FONT_COLOR = "#cccccc";
      
    //NIGHT THEME
    public $LANDING_PAGE_BODY_COLOR = "#273238";
    public $LANDING_PAGE_NAVBAR_COLOR = "#141d26";
    public $LANDING_PAGE_NAVBAR_BUTTON_COLOR = "#99aab5";
    public $LANDING_PAGE_EVENT_BACKGROUND_COLOR = "#273238";
    public $LANDING_PAGE_EVENT_BORDER_COLOR = "#141d26";
    public $LANDING_PAGE_FOOTER_COLOR = "#616161";
  }
?>
